### ISSUE TITLE
Add @JDell0 bio

### ISSUE THREAD

**Issue by JDell0** [githubteacher/foundations-05-19-2015#11]
## Add bio for JDell0
- [ ] Add the bio
- [ ] make sure it's in the bios folder
- [ ] it needs to have the `.md` extension

@JDell0 needs a bio added to the bios folder.

**Comment by githubteacher** [comment]
@JDell0 it looks like you forgot to use the magic words and the issue number in the merge commit when you merged your branch into master. I am going to go ahead and close this issue manually.
