### ISSUE TITLE
Add @mierdin bio

### ISSUE THREAD

**Issue by Mierdin** [githubteacher/foundations-05-19-2015#12]
## Add bio for Matt Oswalt
- [ ] Add the bio
- [ ] make sure it's in the bios folder
- [ ] it needs to have the `.md` extension

@mierdin needs a bio added to the bios folder

**Comment by githubteacher** [comment]
@Mierdin it looks like you forgot to use the magic words and issue number to automatically close this when you merged your branch into master. I am going to go ahead and close this issue manually.
