### ISSUE TITLE
Add @nathanwoerheide bio

### ISSUE THREAD

**Issue by nathanwoerheide** [githubteacher/foundations-05-19-2015#13]
## Add bio for GitHub Nathan
- [ ] Add the bio
- [ ] make sure it's in the bios folder
- [ ] needs to have the ' .md' extension

@nathanwoerheide needs a bio added to the bio folder.

**Comment by githubteacher** [comment]
@nathanwoerheide I noticed your .md didn't render as code. You will actually need to use the back-tick that lives on the same key as the ~ in the top left corner of the keyboard! You can edit your original comment to fix it if you would like.

**Comment by githubteacher** [comment]
@nathanwoerheide it looks like you forgot to use the magic words and the issue number when you merged your pull request. I am going to go ahead and close this issue manually!
