### ISSUE TITLE
Add @ IvangfTSOFT Bio

### ISSUE THREAD

**Issue by Ivanchigo** [githubteacher/foundations-05-19-2015#14]
• [ ] Add the bio
• [ ] Make sure its in the bios folder
• [ ] it needs to have the '.md' extension
@IvangfTSOFT needs a bio added to the bios folder

**Comment by githubteacher** [comment]
@IvangfTSOFT - please add a checklist to your issue!

**Comment by Ivanchigo** [comment]
• [ ] Add the bio
• [ ] Make sure its in the bios folder
• [ ] it needs to have the '.md' extension
@IvangfTSOFT needs a bio added to the bios folder

**Comment by githubteacher** [comment]
@IvangfTSOFT Thank you for adding the checklist. You will notice that the tracker will not appear on the issues list unless the checklist is in the first comment of the issue! 

Be sure to start each item with `- [ ]`

Also, I noticed your .md didn't render as code. You will actually need to use the back-tick that lives on the same key as the ~ in the top left corner of the keyboard!

**Comment by githubteacher** [comment]
@IvangfTSOFT it looks like you forgot to reference this issue in your pull request. I am going to go ahead and manually close this issue.
