### ISSUE TITLE
Add @davejennings09 bio

### ISSUE THREAD

**Issue by davejennings09** [githubteacher/foundations-05-19-2015#16]
- [x] add bio
- [x] make sure in bio folder
- [x] in needs '.md' extension

@davejennings09 needs a bio added to the bios folder.

**Comment by githubteacher** [comment]
@davejennings09 I noticed your .md didn't render as code. You will actually need to use the back-tick that lives on the same key as the ~ in the top left corner of the keyboard! You can edit your original comment to fix it if you would like.
