### ISSUE TITLE
Add @SBero bio

### ISSUE THREAD

**Issue by SBero** [githubteacher/foundations-05-19-2015#17]
## Add bio for GitHub teacher
- [x] Add the bio
- [x] Make sure it's in the bio folder
- [x] It needs to have the `.md` extension

@SBero needs a bio added to the folder

**Comment by githubteacher** [comment]
@SBero it looks like you forgot to include the magic words and the issue number when you merged your branch into master. I am going to go ahead and close this issue manually!
