### ISSUE TITLE
Add @mrmorris bio

### ISSUE THREAD

**Issue by mrmorris** [githubteacher/foundations-05-19-2015#18]
@mrmorris needs a bio
- [x] Open the issue
- [ ] Add the bio
- [ ] make sure it is in the bios folder

Some `code`

**Comment by githubteacher** [comment]
@mrmorris it looks like you forgot to include the magic words and issue number when you merged your branch into master. I am going to go ahead and close this issue manually!

**Comment by mrmorris** [comment]
Oh I missed that part! Do I just reference an issue number when I merge/close the PR?
