### ISSUE TITLE
Add @beccaLozano bio

### ISSUE THREAD

**Issue by beccaLozano** [githubteacher/foundations-05-19-2015#19]
## Add bio for Becca Lozano
- [x] Add bio
- [ ] Make sure it's in the  bio folder
- [ ] Needs to have the `.md` extension

@beccaLozano needs a bio added to the bio folder.

**Comment by githubteacher** [comment]
@beccaLozano I noticed your `.md` didn't render as code. You will actually need to use the back-tick that lives on the same key as the ~ in the top left corner of the keyboard! You can edit your original comment to fix it if you would like.

**Comment by beccaLozano** [comment]
great, thanks!

**Comment by githubteacher** [comment]
Perfect! :+1:

**Comment by githubteacher** [comment]
@beccaLozano it looks like you accidentally referenced you Pull Request when you were merging your branch instead of this issue. That can happen easily when the titles are so similar! I am going to go ahead and close this issue manually!
