### ISSUE TITLE
Add @djcoot12 bio

### ISSUE THREAD

**Issue by ghost** [githubteacher/foundations-05-19-2015#20]
## Add bio for djcoot12
- [x] Add the bio
- [x] Make sure its in the bios folder
- [x] it needs to have the '.md' extension

@djcoot12 needs a bio added to the bios folder

**Comment by githubteacher** [comment]
@djcoot12 I noticed your .md didn't render as code. You will actually need to use the back-tick that lives on the same key as the ~ in the top left corner of the keyboard! You can edit your original comment to fix it if you would like.
