### ISSUE TITLE
.gitconfig question

### ISSUE THREAD

**Issue by cheenpo** [githubteacher/foundations-05-19-2015#39]
is there a way to set the name and email for different repos in the main .gitconfigure file... or do you have to set it up globally and then per repo/folder manually/cli?

**Comment by githubteacher** [comment]
git config setting exist in three places:
- system wide
- user
- local to the repo

You would just use `git config user.name` and `git config user.email` to set them locally for the repository.

**Comment by cheenpo** [comment]
cool beans. so per repo/folder manually. no biggie. it is a set/forget thing I anyways.  thanks!  :smile:
