### ISSUE TITLE
Class focused on Github Pages?

### ISSUE THREAD

**Issue by habber** [githubteacher/foundations-05-19-2015#56]
You mentioned that there is a class every once in a while regarding creating github pages. I've just forked a nice template to use for maintaining our documentation. (habber.github.io), but would like to get better at managing and editing pages... as well as tips for making this a collaborative space for both devs and designers. 

Is the class you mentioned appropriate for what I need to do and if so, do you have a link to a class description and dates?

**Comment by githubteacher** [comment]
@habber I am teaching that class next Wednesday at 9 AM PST. It is a free class and you can sign up for it [here](https://training.github.com/schedule/)

**Comment by habber** [comment]
Thanks! I'll sign up. :+1:
