### ISSUE TITLE
Add @OfCourseITestedIt bio

### ISSUE THREAD

**Issue by DanielSiefert** [githubteacher/foundations-05-19-2015#6]
## Add bio for GitHub Training Participant
- [ ] Add the bio
- [ ] Make sure it's in the bio folder
- [ ] it needs to have the `.md` extension

@OfCourseITestedIt needs a bio added to the bios folder.

**Comment by githubteacher** [comment]
Best user name ever!

**Comment by DanielSiefert** [comment]
Thanks!

**Comment by githubteacher** [comment]
See issue #37 for more information!

**Comment by githubteacher** [comment]
Closing this manually!
